@api = http://localhost:3000

GET {{api}}/users
###
GET {{api}}/user/66074ccc33fdf740578ba082
###
POST  {{api}}/user
Content-Type: application/json

{
    "password" : "xd",
    "email":"xd@gmail.com",
    "user" : "xd xd xd xd"
}
###
PUT  {{api}}/user/65de8d0e8853dc532a6f93f1
Content-Type: application/json

{
    "password" : "Easy"
}

###
DELETE {{api}}/user/66074ccc33fdf740578ba082